#!/bin/bash

# A simple tool to help find broken Python virtual environments. This is
# really only useful and aimed at my macOS setup, where I use Homebrew,
# pyenv, pipenv and generally keep virtual environments inside the
# repository directory (but not inside the repository, I'm not a monster!).
# There are rare occasions where I find all those tools get into a fight and
# I end up with environments that no longer work due to broken symbolic
# links. This helps me quickly check which repositories might be
# problematic.

for venv in $(find . -name .venv)
do
    if ! stat -L "$venv/bin/python" > /dev/null 2>&1
    then
        echo "$(dirname $venv)"
    fi
done

### borked-venvs ends here
